services:
  # 2. TU APLICACIÓN (Lo que tú me pasaste, corregido)
  portfolio:
    image: ghcr.io/mariosangut/mariosangut.com:latest
    container_name: ct_portfolio
    restart: always
    # No necesitas exponer puertos aquí si el proxy está en la misma red
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true