services:
  portfolio:
    image: ghcr.io/mariosangut/www.mariosangut.com:latest
    container_name: ct_portfolio
    restart: always
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true